export const CHECK_CONNECTION = 'CHECK_CONNECTION';
export const FETCH_DETAILS = 'FETCH_DETAILS';
export const RECEIVE_PERSON_RESPONSE = 'RECEIVE_PERSON_RESPONSE';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const INPUT_QUERY = 'INPUT_QUERY';
export const RECEIVE_FACILITY = 'RECEIVE_FACILITY';
export const RECEIVE_EXPOSURE = 'RECEIVE_EXPOSURE';
export const RECEIVE_RESULT = 'RECEIVE_RESULT';